# https://medium.com/@caring_smitten_gerbil_914/understanding-the-conf-d-folder-in-nginx-anatomy-of-default-conf-8d6fc1d59599
events{}

http {
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    server {
        listen 80;
        
        location /{
            return 200 "Hello it is Nginx \n";
        }
    }
}